/*
 * The MIT License
 *
 * Copyright 2014 Daniel Iwaniec, Karol Gos.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import controller.*;

public class MainView extends javax.swing.JFrame {

 public static final String BOX_ICON = "box";
 public static final String HOME_ICON = "home";
 public static final String LICENSE_ICON = "license";

 private static MainView instance = null;

 public static MainView getInstance() {
  if (instance == null) {
   instance = new MainView();
  }
  return instance;
 }

 public MainView() {
  this.getContentPane().setBackground(Color.WHITE);
  this.setExtendedState(MainView.MAXIMIZED_BOTH);
  this.setUndecorated(true);
  this.setLocation(0, 0);

  UIManager.put("PopupMenu.border", BorderFactory.createLineBorder(Color.BLACK, 1));

  initComponents();

  this.hideAllViews();
 }

 public javax.swing.JLabel getHeader() {
  return this.Header;
 }

 public void setIcon(String name) {
  Header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/" + name + ".png")));
 }

 public javax.swing.JPanel getIndexView() {
  return this.Index;
 }

 public javax.swing.JPanel getLicenseView() {
  return this.License;
 }

 public javax.swing.JTextArea getLicenseTextArea() {
  return this.licenseTextArea;
 }

 public javax.swing.JPanel getWarehouseListView() {
  return this.WarehouseList;
 }

 public javax.swing.JPanel getWarehouseFormView() {
  return this.WarehouseForm;
 }

 public javax.swing.JPanel getSelectFormView() {
  return this.SelectForm;
 }

 public javax.swing.JComboBox getSelectFormSelect() {
  return this.SelectFormSelect;
 }

 public javax.swing.JLabel getSelectFormHeader() {
  return this.jLabel17;
 }

 public javax.swing.JButton getSelectFormButton() {
  return this.jButton2;
 }

 public final void hideAllViews() {
  this.WarehouseList.setVisible(false);
  this.WarehouseForm.setVisible(false);
  this.Index.setVisible(false);
  this.License.setVisible(false);
  this.SelectForm.setVisible(false);
 }

 public javax.swing.JTable getWarehouseListTable() {
  return this.jTable1;
 }

 public javax.swing.JTextField getWarehouseFormNameInput() {
  return jTextField1;
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  Header = new javax.swing.JLabel();
  jLayeredPane1 = new javax.swing.JLayeredPane();
  WarehouseList = new javax.swing.JPanel();
  jScrollPane2 = new javax.swing.JScrollPane();
  jTable1 = new javax.swing.JTable();
  WarehouseForm = new javax.swing.JPanel();
  jButton1 = new javax.swing.JButton();
  jTextField1 = new javax.swing.JTextField();
  jLabel1 = new javax.swing.JLabel();
  Index = new javax.swing.JPanel();
  jLabel2 = new javax.swing.JLabel();
  jLabel3 = new javax.swing.JLabel();
  jLabel4 = new javax.swing.JLabel();
  jLabel5 = new javax.swing.JLabel();
  jLabel6 = new javax.swing.JLabel();
  jLabel7 = new javax.swing.JLabel();
  jLabel8 = new javax.swing.JLabel();
  jLabel9 = new javax.swing.JLabel();
  jLabel10 = new javax.swing.JLabel();
  jLabel11 = new javax.swing.JLabel();
  jLabel15 = new javax.swing.JLabel();
  jLabel16 = new javax.swing.JLabel();
  License = new javax.swing.JPanel();
  jLabel12 = new javax.swing.JLabel();
  jLabel13 = new javax.swing.JLabel();
  jLabel14 = new javax.swing.JLabel();
  jScrollPane1 = new javax.swing.JScrollPane();
  licenseTextArea = new javax.swing.JTextArea();
  SelectForm = new javax.swing.JPanel();
  jButton2 = new javax.swing.JButton();
  jLabel17 = new javax.swing.JLabel();
  SelectFormSelect = new javax.swing.JComboBox();
  jMenuBar1 = new javax.swing.JMenuBar();
  jMenu2 = new javax.swing.JMenu();
  jMenuItem7 = new javax.swing.JMenuItem();
  jMenuItem2 = new javax.swing.JMenuItem();
  jMenuItem8 = new javax.swing.JMenuItem();
  jMenu3 = new javax.swing.JMenu();
  jMenuItem3 = new javax.swing.JMenuItem();
  jMenuItem4 = new javax.swing.JMenuItem();
  jMenuItem1 = new javax.swing.JMenuItem();
  jMenuItem5 = new javax.swing.JMenuItem();
  jMenu4 = new javax.swing.JMenu();
  jMenu5 = new javax.swing.JMenu();
  jMenuItem10 = new javax.swing.JMenuItem();
  jMenuItem9 = new javax.swing.JMenuItem();
  jMenu6 = new javax.swing.JMenu();
  jMenuItem11 = new javax.swing.JMenuItem();
  jMenuItem13 = new javax.swing.JMenuItem();

  setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
  setTitle("Magazyn");
  setAlwaysOnTop(true);
  setBackground(new java.awt.Color(255, 255, 255));
  setBounds(new java.awt.Rectangle(0, 0, 0, 0));
  setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
  setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
  setForeground(new java.awt.Color(0, 0, 0));

  Header.setBackground(new java.awt.Color(255, 255, 255));
  Header.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
  Header.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
  Header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/box.png"))); // NOI18N
  Header.setText("MAGAZYNY");
  Header.setToolTipText("");
  Header.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(204, 204, 204)));
  Header.setIconTextGap(20);

  jLayeredPane1.setOpaque(true);

  WarehouseList.setBackground(new java.awt.Color(255, 255, 255));

  jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 427));

  jTable1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
  jTable1.setModel(new javax.swing.table.DefaultTableModel(
   new Object [][] {

   },
   new String [] {
    "ID", "Nazwa"
   }
  ) {
   Class[] types = new Class [] {
    java.lang.Long.class, java.lang.String.class
   };
   boolean[] canEdit = new boolean [] {
    false, false
   };

   public Class getColumnClass(int columnIndex) {
    return types [columnIndex];
   }

   public boolean isCellEditable(int rowIndex, int columnIndex) {
    return canEdit [columnIndex];
   }
  });
  jTable1.setColumnSelectionAllowed(true);
  jTable1.setFillsViewportHeight(true);
  jTable1.setGridColor(new java.awt.Color(204, 204, 204));
  jTable1.setRowHeight(36);
  jTable1.setSelectionBackground(new java.awt.Color(204, 255, 255));
  jTable1.getTableHeader().setReorderingAllowed(false);
  jScrollPane2.setViewportView(jTable1);
  jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
  if (jTable1.getColumnModel().getColumnCount() > 0) {
   jTable1.getColumnModel().getColumn(0).setResizable(false);
   jTable1.getColumnModel().getColumn(1).setResizable(false);
  }

  javax.swing.GroupLayout WarehouseListLayout = new javax.swing.GroupLayout(WarehouseList);
  WarehouseList.setLayout(WarehouseListLayout);
  WarehouseListLayout.setHorizontalGroup(
   WarehouseListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WarehouseListLayout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
    .addContainerGap())
  );
  WarehouseListLayout.setVerticalGroup(
   WarehouseListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(WarehouseListLayout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
    .addContainerGap())
  );

  WarehouseForm.setBackground(new java.awt.Color(255, 255, 255));
  WarehouseForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
  WarehouseForm.setPreferredSize(new java.awt.Dimension(452, 427));

  jButton1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
  jButton1.setText("Dodaj");
  jButton1.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton1ActionPerformed(evt);
   }
  });

  jTextField1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N

  jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
  jLabel1.setLabelFor(jTextField1);
  jLabel1.setText("Nazwa magazynu");

  javax.swing.GroupLayout WarehouseFormLayout = new javax.swing.GroupLayout(WarehouseForm);
  WarehouseForm.setLayout(WarehouseFormLayout);
  WarehouseFormLayout.setHorizontalGroup(
   WarehouseFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(WarehouseFormLayout.createSequentialGroup()
    .addContainerGap()
    .addGroup(WarehouseFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(WarehouseFormLayout.createSequentialGroup()
      .addGap(0, 351, Short.MAX_VALUE)
      .addComponent(jButton1))
     .addGroup(WarehouseFormLayout.createSequentialGroup()
      .addComponent(jLabel1)
      .addGap(0, 0, Short.MAX_VALUE))
     .addComponent(jTextField1))
    .addContainerGap())
  );
  WarehouseFormLayout.setVerticalGroup(
   WarehouseFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WarehouseFormLayout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jLabel1)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
    .addComponent(jButton1)
    .addContainerGap())
  );

  Index.setBackground(new java.awt.Color(255, 255, 255));
  Index.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
  Index.setPreferredSize(new java.awt.Dimension(452, 427));

  jLabel2.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
  jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  jLabel2.setText("Politechnika Świętokrzyska");
  jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

  jLabel3.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
  jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  jLabel3.setText("Programowanie obiektowe Java - Projekt");

  jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
  jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
  jLabel4.setText("Semetr letni 2014r.");

  jLabel5.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
  jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
  jLabel5.setText("Autorzy:");

  jLabel6.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
  jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
  jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/bullet.png"))); // NOI18N
  jLabel6.setText("Daniel Iwaniec");

  jLabel7.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
  jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
  jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/bullet.png"))); // NOI18N
  jLabel7.setText("Karol Gos");

  jLabel8.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
  jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
  jLabel8.setText("Copyright 2014 Daniel Iwaniec, Karol Gos.");

  jLabel9.setFont(new java.awt.Font("Myriad Pro", 1, 16)); // NOI18N
  jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
  jLabel9.setText("Temat projektu: Aplikacja magazynowa.");

  jLabel10.setFont(new java.awt.Font("Myriad Pro", 0, 16)); // NOI18N
  jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
  jLabel10.setText("Projekt obejmuje:");

  jLabel11.setFont(new java.awt.Font("Myriad Pro", 0, 16)); // NOI18N
  jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
  jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/bullet.png"))); // NOI18N
  jLabel11.setText("Dodawanie magazynów.");

  jLabel15.setFont(new java.awt.Font("Myriad Pro", 0, 16)); // NOI18N
  jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
  jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/bullet.png"))); // NOI18N
  jLabel15.setText("Edytowanie magazynów.");

  jLabel16.setFont(new java.awt.Font("Myriad Pro", 0, 16)); // NOI18N
  jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
  jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/bullet.png"))); // NOI18N
  jLabel16.setText("Usuwanie magazynów.");

  javax.swing.GroupLayout IndexLayout = new javax.swing.GroupLayout(Index);
  Index.setLayout(IndexLayout);
  IndexLayout.setHorizontalGroup(
   IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
   .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
   .addGroup(IndexLayout.createSequentialGroup()
    .addContainerGap()
    .addGroup(IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addContainerGap())
  );
  IndexLayout.setVerticalGroup(
   IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(IndexLayout.createSequentialGroup()
    .addGap(5, 5, 5)
    .addComponent(jLabel2)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel3)
    .addGap(18, 18, 18)
    .addComponent(jLabel4)
    .addGap(18, 18, 18)
    .addComponent(jLabel5)
    .addGap(18, 18, 18)
    .addComponent(jLabel6)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel7)
    .addGap(18, 18, 18)
    .addComponent(jLabel9)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel10)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel11)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel15)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel16)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
    .addComponent(jLabel8)
    .addContainerGap())
  );

  License.setBackground(new java.awt.Color(255, 255, 255));
  License.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
  License.setPreferredSize(new java.awt.Dimension(452, 427));

  jLabel12.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
  jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  jLabel12.setText("Politechnika Świętokrzyska");
  jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

  jLabel13.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
  jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  jLabel13.setText("Programowanie obiektowe Java - Projekt");

  jLabel14.setFont(new java.awt.Font("Myriad Pro", 0, 20)); // NOI18N
  jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
  jLabel14.setText("The MIT License");

  jScrollPane1.setBorder(null);

  licenseTextArea.setEditable(false);
  licenseTextArea.setBackground(new java.awt.Color(245, 245, 245));
  licenseTextArea.setColumns(20);
  licenseTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
  licenseTextArea.setRows(5);
  licenseTextArea.setBorder(null);
  jScrollPane1.setViewportView(licenseTextArea);

  javax.swing.GroupLayout LicenseLayout = new javax.swing.GroupLayout(License);
  License.setLayout(LicenseLayout);
  LicenseLayout.setHorizontalGroup(
   LicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
   .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LicenseLayout.createSequentialGroup()
    .addContainerGap()
    .addGroup(LicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
     .addComponent(jScrollPane1)
     .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addContainerGap())
  );
  LicenseLayout.setVerticalGroup(
   LicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(LicenseLayout.createSequentialGroup()
    .addGap(5, 5, 5)
    .addComponent(jLabel12)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel13)
    .addGap(18, 18, 18)
    .addComponent(jLabel14)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
    .addContainerGap())
  );

  SelectForm.setBackground(new java.awt.Color(255, 255, 255));
  SelectForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
  SelectForm.setPreferredSize(new java.awt.Dimension(452, 427));

  jButton2.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
  jButton2.setText("OK");
  jButton2.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton2ActionPerformed(evt);
   }
  });

  jLabel17.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
  jLabel17.setLabelFor(jTextField1);
  jLabel17.setText("Wybierz");

  SelectFormSelect.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
  SelectFormSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

  javax.swing.GroupLayout SelectFormLayout = new javax.swing.GroupLayout(SelectForm);
  SelectForm.setLayout(SelectFormLayout);
  SelectFormLayout.setHorizontalGroup(
   SelectFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(SelectFormLayout.createSequentialGroup()
    .addContainerGap()
    .addGroup(SelectFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(SelectFormLayout.createSequentialGroup()
      .addGap(0, 423, Short.MAX_VALUE)
      .addComponent(jButton2))
     .addGroup(SelectFormLayout.createSequentialGroup()
      .addComponent(jLabel17)
      .addGap(0, 0, Short.MAX_VALUE))
     .addComponent(SelectFormSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addContainerGap())
  );
  SelectFormLayout.setVerticalGroup(
   SelectFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectFormLayout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jLabel17)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(SelectFormSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 451, Short.MAX_VALUE)
    .addComponent(jButton2)
    .addContainerGap())
  );

  javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
  jLayeredPane1.setLayout(jLayeredPane1Layout);
  jLayeredPane1Layout.setHorizontalGroup(
   jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(WarehouseList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
   .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jLayeredPane1Layout.createSequentialGroup()
     .addContainerGap()
     .addComponent(WarehouseForm, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
     .addContainerGap()))
   .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jLayeredPane1Layout.createSequentialGroup()
     .addContainerGap()
     .addComponent(Index, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
     .addContainerGap()))
   .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jLayeredPane1Layout.createSequentialGroup()
     .addContainerGap()
     .addComponent(License, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
     .addContainerGap()))
   .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jLayeredPane1Layout.createSequentialGroup()
     .addContainerGap()
     .addComponent(SelectForm, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
     .addContainerGap()))
  );
  jLayeredPane1Layout.setVerticalGroup(
   jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(WarehouseList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
   .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jLayeredPane1Layout.createSequentialGroup()
     .addGap(10, 10, 10)
     .addComponent(WarehouseForm, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
     .addContainerGap()))
   .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jLayeredPane1Layout.createSequentialGroup()
     .addGap(10, 10, 10)
     .addComponent(Index, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
     .addContainerGap()))
   .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jLayeredPane1Layout.createSequentialGroup()
     .addContainerGap()
     .addComponent(License, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
     .addGap(21, 21, 21)))
   .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jLayeredPane1Layout.createSequentialGroup()
     .addContainerGap()
     .addComponent(SelectForm, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
     .addGap(21, 21, 21)))
  );
  jLayeredPane1.setLayer(WarehouseList, javax.swing.JLayeredPane.DEFAULT_LAYER);

  WarehouseList.getAccessibleContext().setAccessibleName("WarehouseList");
  jLayeredPane1.setLayer(WarehouseForm, javax.swing.JLayeredPane.DEFAULT_LAYER);
  WarehouseForm.getAccessibleContext().setAccessibleName("WarehouseForm");
  jLayeredPane1.setLayer(Index, javax.swing.JLayeredPane.DEFAULT_LAYER);
  Index.getAccessibleContext().setAccessibleName("Index");
  jLayeredPane1.setLayer(License, javax.swing.JLayeredPane.DEFAULT_LAYER);
  License.getAccessibleContext().setAccessibleName("License");
  jLayeredPane1.setLayer(SelectForm, javax.swing.JLayeredPane.DEFAULT_LAYER);
  SelectForm.getAccessibleContext().setAccessibleName("SelectForm");

  jMenuBar1.setBorderPainted(false);

  jMenu2.setText("Aplikacja");

  jMenuItem7.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
  jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/home_small.png"))); // NOI18N
  jMenuItem7.setText("Informacje o projekcie");
  jMenuItem7.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
  jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem7ActionPerformed(evt);
   }
  });
  jMenu2.add(jMenuItem7);

  jMenuItem2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
  jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/license_menu.png"))); // NOI18N
  jMenuItem2.setText("Licencja");
  jMenuItem2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
  jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem2ActionPerformed(evt);
   }
  });
  jMenu2.add(jMenuItem2);

  jMenuItem8.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
  jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/exit.png"))); // NOI18N
  jMenuItem8.setText("Zakończ");
  jMenuItem8.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
  jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem8ActionPerformed(evt);
   }
  });
  jMenu2.add(jMenuItem8);

  jMenuBar1.add(jMenu2);

  jMenu3.setText("Magazyn");
  jMenu3.setBorderPainted(true);

  jMenuItem3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
  jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/list.png"))); // NOI18N
  jMenuItem3.setText("Lista");
  jMenuItem3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
  jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem3ActionPerformed(evt);
   }
  });
  jMenu3.add(jMenuItem3);

  jMenuItem4.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
  jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/add.png"))); // NOI18N
  jMenuItem4.setText("Dodaj");
  jMenuItem4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
  jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem4ActionPerformed(evt);
   }
  });
  jMenu3.add(jMenuItem4);

  jMenuItem1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
  jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/edit.png"))); // NOI18N
  jMenuItem1.setText("Edytuj");
  jMenuItem1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
  jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem1ActionPerformed(evt);
   }
  });
  jMenu3.add(jMenuItem1);

  jMenuItem5.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
  jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icon/delete.png"))); // NOI18N
  jMenuItem5.setText("Usuń");
  jMenuItem5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
  jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jMenuItem5ActionPerformed(evt);
   }
  });
  jMenu3.add(jMenuItem5);

  jMenuBar1.add(jMenu3);

  jMenu4.setText("Dokument");

  jMenu5.setText("Wydanie zewnętrzne");

  jMenuItem10.setText("Lista");
  jMenu5.add(jMenuItem10);

  jMenuItem9.setText("Dodaj");
  jMenu5.add(jMenuItem9);

  jMenu4.add(jMenu5);

  jMenu6.setText("Przyjęcie zewnętrzne");

  jMenuItem11.setText("Lista");
  jMenu6.add(jMenuItem11);

  jMenuItem13.setText("Dodaj");
  jMenu6.add(jMenuItem13);

  jMenu4.add(jMenu6);

  jMenuBar1.add(jMenu4);

  setJMenuBar(jMenuBar1);

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addComponent(Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jLayeredPane1)
    .addContainerGap())
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(Header)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(jLayeredPane1)
    .addContainerGap())
  );

  Header.getAccessibleContext().setAccessibleName("Header");

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
  WarehouseController.list();
 }//GEN-LAST:event_jMenuItem3ActionPerformed

 private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try {
   WarehouseController.addAction();
  } catch (Exception ex) {
   Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
  }
 }//GEN-LAST:event_jButton1ActionPerformed

 private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
  WarehouseController.addForm();
 }//GEN-LAST:event_jMenuItem4ActionPerformed

 private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
  main.Main.mainAction();
 }//GEN-LAST:event_jMenuItem7ActionPerformed

 private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
  this.dispose();
 }//GEN-LAST:event_jMenuItem8ActionPerformed

 private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
  WarehouseController.deleteForm();
 }//GEN-LAST:event_jMenuItem5ActionPerformed

 private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
  main.Main.licenseAction();
 }//GEN-LAST:event_jMenuItem2ActionPerformed

 private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  // TODO add your handling code here:
 }//GEN-LAST:event_jButton2ActionPerformed

 private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
  WarehouseController.editSelectForm();
 }//GEN-LAST:event_jMenuItem1ActionPerformed

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
   * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
   */
  try {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) {
   java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex) {
   java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   @Override
   public void run() {
    new MainView().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JLabel Header;
 private javax.swing.JPanel Index;
 private javax.swing.JPanel License;
 private javax.swing.JPanel SelectForm;
 private javax.swing.JComboBox SelectFormSelect;
 private javax.swing.JPanel WarehouseForm;
 private javax.swing.JPanel WarehouseList;
 private javax.swing.JButton jButton1;
 private javax.swing.JButton jButton2;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel10;
 private javax.swing.JLabel jLabel11;
 private javax.swing.JLabel jLabel12;
 private javax.swing.JLabel jLabel13;
 private javax.swing.JLabel jLabel14;
 private javax.swing.JLabel jLabel15;
 private javax.swing.JLabel jLabel16;
 private javax.swing.JLabel jLabel17;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JLabel jLabel5;
 private javax.swing.JLabel jLabel6;
 private javax.swing.JLabel jLabel7;
 private javax.swing.JLabel jLabel8;
 private javax.swing.JLabel jLabel9;
 private javax.swing.JLayeredPane jLayeredPane1;
 private javax.swing.JMenu jMenu2;
 private javax.swing.JMenu jMenu3;
 private javax.swing.JMenu jMenu4;
 private javax.swing.JMenu jMenu5;
 private javax.swing.JMenu jMenu6;
 private javax.swing.JMenuBar jMenuBar1;
 private javax.swing.JMenuItem jMenuItem1;
 private javax.swing.JMenuItem jMenuItem10;
 private javax.swing.JMenuItem jMenuItem11;
 private javax.swing.JMenuItem jMenuItem13;
 private javax.swing.JMenuItem jMenuItem2;
 private javax.swing.JMenuItem jMenuItem3;
 private javax.swing.JMenuItem jMenuItem4;
 private javax.swing.JMenuItem jMenuItem5;
 private javax.swing.JMenuItem jMenuItem7;
 private javax.swing.JMenuItem jMenuItem8;
 private javax.swing.JMenuItem jMenuItem9;
 private javax.swing.JScrollPane jScrollPane1;
 private javax.swing.JScrollPane jScrollPane2;
 private javax.swing.JTable jTable1;
 private javax.swing.JTextField jTextField1;
 private javax.swing.JTextArea licenseTextArea;
 // End of variables declaration//GEN-END:variables
}
